[server]
bind_addr = "0.0.0.0:"
heartbeat_interval = 15

[server.transport]
type = "tcp"

[server.transport.tcp]
nodelay = true
keepalive_secs = 20
keepalive_interval = 8

[server.services.socks]
type = "tcp"
token = ""
bind_addr = "127.0.0.1:10801"
nodelay = true

[server.services.http]
type = "tcp"
token = ""
bind_addr = "127.0.0.1:10802"
nodelay = true

[server.services.vless]
type = "tcp"
token = ""
bind_addr = "0.0.0.0:10803"
nodelay = true
